from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class GuaGuaArtRoomAssets: 


	# Click Rule Assets
	# 左侧随机点击区域 
	C_RANDOM_LEFT = RuleClick(roi_front=(17,84,104,356), roi_back=(17,81,106,365), name="random_left")
	# 右侧随机点击区域 
	C_RANDOM_RIGHT = RuleClick(roi_front=(1133,88,131,361), roi_back=(1131,84,133,363), name="random_right")


	# Image Rule Assets
	# 庭院右侧进入呱呱画室活动入口 
	I_MAIN_GOTO_ACT = RuleImage(roi_front=(1190,300,46,66), roi_back=(1164,134,83,393), threshold=0.7, method="Template matching", file="./tasks/GuaGuaArtRoom/ga/ga_main_goto_act.png")
	# 活动总览页呱呱画室主界面检测 
	I_CHECK_ACT_MAIN = RuleImage(roi_front=(691,62,242,64), roi_back=(680,55,260,80), threshold=0.7, method="Template matching", file="./tasks/GuaGuaArtRoom/ga/ga_check_act_main.png")
	# 活动总览页获取颜料按钮 
	I_TO_PAINT_COLLECTION = RuleImage(roi_front=(1156,449,62,65), roi_back=(1130,420,120,120), threshold=0.7, method="Template matching", file="./tasks/GuaGuaArtRoom/ga/ga_to_paint_collection.png")
	# 获取颜料页面检测 
	I_CHECK_PAINT_COLLECTION = RuleImage(roi_front=(166,22,129,35), roi_back=(160,18,140,45), threshold=0.7, method="Template matching", file="./tasks/GuaGuaArtRoom/ga/ga_check_paint_collection.png")
	# 获取颜料页右下角挑战按钮 
	I_PAINT_CHALLENGE = RuleImage(roi_front=(1115,595,99,74), roi_back=(1090,570,150,130), threshold=0.8, method="Template matching", file="./tasks/GuaGuaArtRoom/ga/ga_paint_challenge.png")
	# 颜料上限弹窗前往提交按钮 
	I_GO_SUBMIT = RuleImage(roi_front=(698,418,132,40), roi_back=(680,400,170,80), threshold=0.8, method="Template matching", file="./tasks/GuaGuaArtRoom/ga/ga_go_submit.png")
	# 活动主页面提交颜料按钮 
	I_SUBMIT_PAINT = RuleImage(roi_front=(1151,593,117,129), roi_back=(1130,570,160,160), threshold=0.7, method="Template matching", file="./tasks/GuaGuaArtRoom/ga/ga_submit_paint.png")


	# Ocr Rule Assets
	# 左下角今日可得数值 
	O_REMAIN_REWARD = RuleOcr(roi=(130,591,31,26), area=(130,591,31,26), mode="Digit", method="Default", keyword="", name="remain_reward")


