from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class AbyssIllusionAssets: 


	# Click Rule Assets
	# 左侧随机点击区域 
	C_RANDOM_LEFT = RuleClick(roi_front=(17,84,104,356), roi_back=(17,81,106,365), name="random_left")
	# 右侧随机点击区域 
	C_RANDOM_RIGHT = RuleClick(roi_front=(1133,88,131,361), roi_back=(1131,84,133,363), name="random_right")


	# Image Rule Assets
	# 庭院右侧进入狭间幻境活动入口 
	I_MAIN_GOTO_ACT = RuleImage(roi_front=(1180,300,60,64), roi_back=(1160,134,100,393), threshold=0.7, method="Template matching", file="./tasks/AbyssIllusion/ai/ai_main_goto_act.png")
	# 活动主界面检测 
	I_CHECK_ACT_MAIN = RuleImage(roi_front=(60,15,170,50), roi_back=(50,10,190,60), threshold=0.7, method="Template matching", file="./tasks/AbyssIllusion/ai/ai_check_act_main.png")
	# 活动主界面狭间幻境入口按钮 
	I_TO_ABYSS_ILLUSION = RuleImage(roi_front=(37,572,106,119), roi_back=(20,550,140,150), threshold=0.7, method="Template matching", file="./tasks/AbyssIllusion/ai/ai_to_abyss_illusion.png")
	# 狭间幻境挑战界面检测 
	I_CHECK_ABYSS_ILLUSION_MAIN = RuleImage(roi_front=(70,15,220,50), roi_back=(60,10,240,60), threshold=0.7, method="Template matching", file="./tasks/AbyssIllusion/ai/ai_check_abyss_illusion_main.png")
	# 狭间幻境挑战按钮 
	I_CHALLENGE = RuleImage(roi_front=(1090,570,150,110), roi_back=(1070,550,190,150), threshold=0.8, method="Template matching", file="./tasks/AbyssIllusion/ai/ai_challenge.png")


	# Ocr Rule Assets
	# 挑战券数量 
	O_REMAIN_TICKETS = RuleOcr(roi=(1160,20,100,40), area=(1160,20,100,40), mode="DigitCounter", method="Default", keyword="", name="remain_tickets")


