from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class BuyWindowAssets: 


	# Click Rule Assets
	# 点击弹窗外部半透明安全区域关闭购买弹窗 
	C_TICKET_BUY_CLOSE_SAFE = RuleClick(roi_front=(50,300,80,150), roi_back=(50,300,80,150), name="ticket_buy_close_safe")


	# Image Rule Assets
	# 活动门票购买弹窗-左侧魂玉购买图标 
	I_TICKET_BUY_RMB = RuleImage(roi_front=(372,606,35,32), roi_back=(300,560,200,120), threshold=0.8, method="Template matching", file="./tasks/Component/BuyWindow/bw/bw_ticket_buy_rmb.png")
	# 活动门票购买弹窗-右侧勾玉购买图标 
	I_TICKET_BUY_JADE = RuleImage(roi_front=(832,598,36,42), roi_back=(760,560,200,120), threshold=0.8, method="Template matching", file="./tasks/Component/BuyWindow/bw/bw_ticket_buy_jade.png")


