from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class DuelAssets: 


	# Click Rule Assets
	# 战斗数据 
	C_D_BATTLE_DATA = RuleClick(roi_front=(584,279,100,100), roi_back=(584,279,100,100), name="d_battle_data")
	# 自动上阵齿轮按钮 
	C_D_AUTO_ENTRY = RuleClick(roi_front=(15,110,70,70), roi_back=(15,110,70,70), name="d_auto_entry")
	# 准备鼓按钮 
	C_D_PREPARE = RuleClick(roi_front=(1130,550,120,120), roi_back=(1130,550,120,120), name="d_prepare")
	# 战斗左下角自动/手动切换点击位 
	C_D_BATTLE_SWITCH_AUTO = RuleClick(roi_front=(25,635,70,55), roi_back=(25,635,70,55), name="d_battle_switch_auto")


	# Image Rule Assets
	# 点击阵容 
	I_D_TEAM = RuleImage(roi_front=(813,288,34,74), roi_back=(785,259,115,119), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_team.png")
	# 一键切换所有的御魂 
	I_D_TEAM_SWTICH = RuleImage(roi_front=(1082,85,38,41), roi_back=(1082,85,38,41), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_team_swtich.png")
	# description 
	I_D_BATTLE = RuleImage(roi_front=(1153,573,100,100), roi_back=(1123,537,154,177), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_battle.png")
	# 战斗带保护的 
	I_D_BATTLE_PROTECT = RuleImage(roi_front=(1153,578,100,100), roi_back=(1118,553,155,149), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_battle_protect.png")
	# 自动上阵 
	I_D_AUTO_ENTRY = RuleImage(roi_front=(23,118,53,54), roi_back=(0,95,110,105), threshold=0.75, method="Template matching", file="./tasks/Duel/duel/duel_d_auto_entry.png")
	# 主界面的感叹号 
	I_D_HELP = RuleImage(roi_front=(783,500,29,30), roi_back=(778,476,49,78), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_help.png")
	# 准备 
	I_D_PREPARE = RuleImage(roi_front=(1127,541,100,100), roi_back=(1110,520,140,150), threshold=0.75, method="Template matching", file="./tasks/Duel/duel/duel_d_prepare.png")
	# 胜利 
	I_D_VICTORY = RuleImage(roi_front=(433,76,100,100), roi_back=(433,76,100,100), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_victory.png")
	# 失败 
	I_D_FAIL = RuleImage(roi_front=(422,66,100,100), roi_back=(422,66,100,100), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_fail.png")
	# 战 
	I_D_WORD_BATTLE = RuleImage(roi_front=(613,41,54,54), roi_back=(600,24,84,85), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_word_battle.png")
	# 练 
	I_BATTLE_WITH_TRAIN = RuleImage(roi_front=(1161,588,78,81), roi_back=(1114,547,163,172), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_battle_with_train.png")
	# 练2 
	I_BATTLE_WITH_TRAIN2 = RuleImage(roi_front=(1161,588,78,81), roi_back=(1114,547,163,172), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_battle_with_train2.png")
	# 斗技模式（普通） 
	I_BATTLE_TYPE_COMMON = RuleImage(roi_front=(439,278,90,88), roi_back=(439,278,90,88), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_battle_type_common.png")
	# 活动的战斗按钮 
	I_D_BATTLE2 = RuleImage(roi_front=(1171,592,69,78), roi_back=(1119,566,154,143), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_battle2.png")
	# 左上角的退出 
	I_DUEL_EXIT = RuleImage(roi_front=(14,12,43,41), roi_back=(14,12,43,41), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_duel_exit.png")
	# 斗技荣誉图标 
	I_DUEL_HONOR = RuleImage(roi_front=(211,636,20,20), roi_back=(200,601,130,100), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_duel_honor.png")
	# 胜利分享 
	I_D_WIN_SHARE = RuleImage(roi_front=(1123,608,82,73), roi_back=(1123,608,82,73), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/d_win_share.png")
	# 名士星标 
	I_D_CELEB_STAR = RuleImage(roi_front=(620,450,40,40), roi_back=(450,400,350,150), threshold=0.75, method="Template matching", file="./tasks/Duel/duel/duel_d_celeb_star.png")
	# 名士荣誉殿堂图标 
	I_D_CELEB_HONOR = RuleImage(roi_front=(150,640,50,50), roi_back=(80,600,180,100), threshold=0.75, method="Template matching", file="./tasks/Duel/duel/duel_d_celeb_honor.png")
	# 小白弹窗 
	I_WHITE_DOG = RuleImage(roi_front=(388,327,70,62), roi_back=(308,254,215,249), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_white_dog.png")


	# Ocr Rule Assets
	# 荣誉 
	O_D_HONOR = RuleOcr(roi=(233,644,131,31), area=(233,643,131,31), mode="DigitCounter", method="Default", keyword="", name="d_honor")
	# 分数 
	O_D_SCORE = RuleOcr(roi=(604,484,108,28), area=(604,484,108,28), mode="DigitCounter", method="Default", keyword="", name="d_score")
	# 名士星数 
	O_D_CELEB_STAR_COUNT = RuleOcr(roi=(640,445,80,40), area=(640,445,80,40), mode="Digit", method="Default", keyword="", name="d_celeb_star_count")
	# 自动上阵按钮 
	O_D_AUTO_ENTRY = RuleOcr(roi=(10,105,80,80), area=(10,105,80,80), mode="Full", method="Default", keyword="上阵", name="d_auto_entry")
	# 取消自动上阵按钮（已开启状态） 
	O_D_AUTO_ENTRY_CANCEL = RuleOcr(roi=(10,105,80,80), area=(10,105,80,80), mode="Full", method="Default", keyword="取消", name="d_auto_entry_cancel")
	# 准备鼓按钮 
	O_D_PREPARE = RuleOcr(roi=(1120,530,150,180), area=(1120,530,150,180), mode="Full", method="Default", keyword="准备", name="d_prepare")
	# 已确定鼓按钮（已就绪状态） 
	O_D_PREPARE_DONE = RuleOcr(roi=(1120,530,150,180), area=(1120,530,150,180), mode="Full", method="Default", keyword="确定", name="d_prepare_done")
	# 战斗手动模式标志 
	O_D_BATTLE_HAND = RuleOcr(roi=(20,630,80,65), area=(20,630,80,65), mode="Full", method="Default", keyword="手动", name="d_battle_hand")
	# 战斗自动模式标志 
	O_D_BATTLE_AUTO = RuleOcr(roi=(20,630,80,65), area=(20,630,80,65), mode="Full", method="Default", keyword="自动", name="d_battle_auto")


