from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class DailyTriflesAssets: 


	# Image Rule Assets
	# 进入庭院事务标志 
	I_ENTER_COURTYARD_AFFAIRS = RuleImage(roi_front=(990,372,25,30), roi_back=(696,349,343,231), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/dt/dt_enter_courtyard_affairs.png")
	# 庭院事务页面标志 
	I_CHECK_COURTYARD_AFFAIRS = RuleImage(roi_front=(254,40,196,57), roi_back=(134,0,415,180), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/dt/dt_check_courtyard_affairs.png")
	# 一键完成标志 
	I_ONE_COMPLETE = RuleImage(roi_front=(1114,589,93,93), roi_back=(1083,562,163,139), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/dt/dt_one_complete.png")
	# 右上角进入日常 
	I_ENTER_DAILY = RuleImage(roi_front=(1131,122,84,76), roi_back=(1117,98,136,226), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/dt/dt_enter_daily.png")
	# 右上角检查是否在日常中 
	I_CHECK_IN_DAILY = RuleImage(roi_front=(1131,115,106,88), roi_back=(1128,94,151,281), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/dt/dt_check_in_daily.png")


	# Image Rule Assets
	# 全部收取 
	I_HARVEST_MAIL_ALL = RuleImage(roi_front=(69,579,80,67), roi_back=(28,551,142,144), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/dt/dt_harvest_mail_all.png")
	# 一键已读所有邮件 
	I_READ_ALL_MAIL = RuleImage(roi_front=(180,605,130,35), roi_back=(149,588,182,72), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/dt/dt_read_all_mail.png")
	# 确认收取邮件 
	I_HARVEST_MAIL_CONFIRM = RuleImage(roi_front=(687,543,168,64), roi_back=(687,543,168,64), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/dt/dt_harvest_mail_confirm.png")
	# 邮件图标 
	I_DT_HARVEST_MAIL_COPY = RuleImage(roi_front=(1156,15,29,21), roi_back=(1127,0,80,60), threshold=0.7, method="Template matching", file="./tasks/DailyTrifles/dt/dt_harvest_mail_copy.png")


	# Image Rule Assets
	# description 
	I_L_FRIENDS = RuleImage(roi_front=(67,625,70,72), roi_back=(67,625,70,72), threshold=0.9, method="Template matching", file="./tasks/DailyTrifles/love/love_l_friends.png")
	# description 
	I_L_LOVE = RuleImage(roi_front=(123,625,67,72), roi_back=(123,625,67,72), threshold=0.9, method="Template matching", file="./tasks/DailyTrifles/love/love_l_love.png")
	# 一键收取 
	I_L_COLLECT = RuleImage(roi_front=(47,537,129,56), roi_back=(47,537,129,56), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/love/love_l_collect.png")
	# 一键祝福 
	I_ONE_CLICK_BLESS = RuleImage(roi_front=(1115,500,93,33), roi_back=(1115,500,93,33), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/love/Screenshots_one_click_bless.png")
	# 点击祝福 
	I_CLICK_BLESS = RuleImage(roi_front=(617,442,92,39), roi_back=(617,442,92,39), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/love/Screenshots_click_bless.png")
	# 吉闻页 
	I_LUCK_TITLE = RuleImage(roi_front=(600,52,131,67), roi_back=(600,52,131,67), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/love/Screenshots_luck_title.png")
	# 好友羁绊提升弹窗 
	I_FRIENDSHIP_UP = RuleImage(roi_front=(1147,80,27,28), roi_back=(1147,80,27,28), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/love/friendship_up.png")
	# 吉闻关闭的红色按钮,必须与好友的关闭按钮进行区分 
	I_CLOSE_LUCK_RED = RuleImage(roi_front=(1063,129,30,30), roi_back=(1010,84,127,128), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/love/love_close_luck_red.png")


	# Ocr Rule Assets
	#  
	O_LUCK_MSG = RuleOcr(roi=(15,27,68,61), area=(0,8,100,100), mode="Full", method="Default", keyword="吉闻", name="luck_msg")


	# Click Rule Assets
	# 御魂详细 
	C_ST_DETAIL = RuleClick(roi_front=(1188,318,87,74), roi_back=(1190,317,87,74), name="st_detail")
	# 出现神赐 
	C_ST_GOD_PRSENT = RuleClick(roi_front=(717,165,100,48), roi_back=(926,165,100,54), name="st_god_prsent")


	# Image Rule Assets
	# 点击御魂 
	I_ST_SOULS = RuleImage(roi_front=(1170,226,70,80), roi_back=(1170,226,70,80), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/simple/simple_st_souls.png")
	# 更换 
	I_ST_REPLACE = RuleImage(roi_front=(856,170,100,100), roi_back=(856,170,100,100), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/simple/simple_st_replace.png")
	# 奉纳 
	I_ST_BONGNA = RuleImage(roi_front=(1154,202,77,97), roi_back=(1154,202,77,97), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/simple/simple_st_bongna.png")
	# 贪吃鬼 
	I_ST_GREED = RuleImage(roi_front=(1157,611,65,60), roi_back=(1157,611,65,60), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/simple/simple_st_greed.png")
	# 整理 
	I_ST_TIDY = RuleImage(roi_front=(1155,328,74,100), roi_back=(1155,328,74,100), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/simple/simple_st_tidy.png")
	# 进食习惯 
	I_ST_GREED_HABIT = RuleImage(roi_front=(817,529,165,61), roi_back=(817,529,165,61), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/simple/simple_st_greed_habit.png")
	# 立即进食 
	I_ST_FEED_NOW = RuleImage(roi_front=(929,593,73,65), roi_back=(929,593,73,65), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/simple/simple_st_feed_now.png")
	# 未选中 
	I_ST_UNSELECTED = RuleImage(roi_front=(542,342,38,37), roi_back=(542,342,38,37), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/simple/simple_st_unselected.png")
	# 关闭贪吃鬼 
	I_ST_GREED_CLOSE = RuleImage(roi_front=(933,211,35,37), roi_back=(933,211,35,37), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/simple/simple_st_greed_close.png")
	# 招财猫 
	I_ST_CAT = RuleImage(roi_front=(799,269,147,133), roi_back=(799,269,147,133), threshold=0.7, method="Template matching", file="./tasks/DailyTrifles/simple/simple_st_cat.png")
	# 奉纳 
	I_ST_DONATE = RuleImage(roi_front=(813,628,126,68), roi_back=(813,628,126,68), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/simple/simple_st_donate.png")
	# 神赐 
	I_ST_GOD_PRESENT = RuleImage(roi_front=(578,234,131,73), roi_back=(542,117,204,219), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/simple/simple_st_god_present.png")
	# 已弃置被选中 
	I_ST_ABANDONED_SELECTED = RuleImage(roi_front=(32,112,107,52), roi_back=(15,89,139,87), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/simple/simple_st_abandoned_selected.png")
	# 第一个御魂是+0的 
	I_ST_LEVEL_0 = RuleImage(roi_front=(85,235,45,30), roi_back=(85,235,45,30), threshold=0.9, method="Template matching", file="./tasks/DailyTrifles/simple/simple_st_level_0.png")
	# 御魂奉纳后获得的金币 
	I_ST_GOLD = RuleImage(roi_front=(170,100,950,500), roi_back=(170,100,950,500), threshold=0.9, method="Template matching", file="./tasks/DailyTrifles/simple/simple_st_gold.png")
	# 御魂溢出 
	I_ST_SOUL_OVERFLOW = RuleImage(roi_front=(447,260,384,42), roi_back=(447,260,384,42), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/simple/simple_st_soul_overflow.png")
	# 御魂关闭状态 
	I_ST_SOULS_CLOSE = RuleImage(roi_front=(1180,227,56,83), roi_back=(1166,215,84,107), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/simple/simple_st_souls_close.png")
	# 狗粮御魂的堆叠标识 
	I_ST_SOUL_STACK = RuleImage(roi_front=(142,234,20,16), roi_back=(137,228,407,32), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/simple/simple_st_soul_stack.png")


	# Long Click Rule Assets
	# description 
	L_ONE = RuleLongClick(roi_front=(88,272,100,78), roi_back=(88,272,100,78), duration=1500, name="one")


	# Ocr Rule Assets
	# 奉纳获得的金币 
	O_ST_GOLD = RuleOcr(roi=(888,575,105,32), area=(888,575,105,32), mode="Digit", method="Default", keyword="", name="st_gold")
	# 奉纳的御魂等级 
	O_ST_FIRSET_LEVEL = RuleOcr(roi=(91,237,35,28), area=(91,237,35,28), mode="Single", method="Default", keyword="", name="st_firset_level")
	# 入手顺序 
	O_ST_SORT_TIME = RuleOcr(roi=(387,118,110,42), area=(387,118,110,42), mode="Single", method="Default", keyword="入手顺序", name="st_sort_time")
	# 等级/星级 最上边的 
	O_ST_SORT_LEVEL_1 = RuleOcr(roi=(384,115,121,45), area=(384,115,121,45), mode="Single", method="Default", keyword="等级/星级", name="st_sort_level_1")
	# 等级/星 下边的 
	O_ST_SORT_LEVEL_2 = RuleOcr(roi=(400,290,128,42), area=(400,290,128,42), mode="Single", method="Default", keyword="等级/星级", name="st_sort_level_2")
	# 类型 
	O_ST_SORT_TYPE = RuleOcr(roi=(414,118,64,43), area=(414,118,64,43), mode="Single", method="Default", keyword="类型", name="st_sort_type")
	# 位置 
	O_ST_SORT_LOCATION = RuleOcr(roi=(415,119,61,39), area=(415,119,61,39), mode="Single", method="Default", keyword="位置", name="st_sort_location")
	# Ocr-description 
	O_ST_OVERFLOW = RuleOcr(roi=(686,397,109,48), area=(686,397,109,48), mode="Single", method="Default", keyword="知道了", name="st_overflow")


	# 以下资源原属 tasks/Pets，已融入 DailyTrifles
	# Image Rule Assets
	# 宠物小屋
	I_PET_HOUSE = RuleImage(roi_front=(1012,414,56,25), roi_back=(952,412,144,60), threshold=0.7, method="Template matching", file="./tasks/DailyTrifles/pet/pet_pet_house.png")
	# 爪印
	I_PET_CLAW = RuleImage(roi_front=(1171,625,55,56), roi_back=(1171,625,55,56), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/pet/pet_pet_claw.png")
	# 快速喂养
	I_PET_FEAST = RuleImage(roi_front=(849,624,69,49), roi_back=(849,624,69,49), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/pet/pet_pet_feast.png")
	# 喂食
	I_PET_FEED = RuleImage(roi_front=(899,511,79,68), roi_back=(884,485,127,123), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/pet/pet_pet_feed.png")
	# 跳过
	I_PET_SKIP = RuleImage(roi_front=(1089,119,72,41), roi_back=(999,42,242,147), threshold=0.65, method="Template matching", file="./tasks/DailyTrifles/pet/pet_pet_skip.png")


	# Ocr Rule Assets
	# 喂食的体力
	O_PET_FEED_AP = RuleOcr(roi=(817,538,57,33), area=(817,538,57,33), mode="Digit", method="Default", keyword="", name="pet_feed_ap")
	# 玩耍的体力
	O_PET_PLAY_GOLD = RuleOcr(roi=(681,524,74,40), area=(681,524,74,40), mode="Digit", method="Default", keyword="", name="pet_play_gold")


	# Image Rule Assets
	# 礼包屋 
	I_ROOM_GIFT = RuleImage(roi_front=(1138,658,52,40), roi_back=(1119,621,103,94), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/store/store_room_gift.png")
	# description 
	I_GIFT_RECOMMEND = RuleImage(roi_front=(1183,454,53,64), roi_back=(1162,77,98,457), threshold=0.7, method="Template matching", file="./tasks/DailyTrifles/store/store_gift_recommend.png")
	# 免费一抽领黑蛋 
	I_GIFT_SIGN = RuleImage(roi_front=(186,191,115,83), roi_back=(130,129,891,473), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/store/store_gift_sign.png")


	# Image Rule Assets
	# 点击今忆召唤票 
	I_RECALL_TICKET = RuleImage(roi_front=(595,586,65,76), roi_back=(595,586,65,76), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/summonRecall/recall_ticket.png")
	# 今忆召唤单抽 
	I_RECALL_ONE_TICKET = RuleImage(roi_front=(459,604,76,76), roi_back=(459,604,76,76), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/summonRecall/recall_one_ticket.png")
	# description 
	I_RECALL_SM_CONFIRM = RuleImage(roi_front=(424,628,174,61), roi_back=(424,628,174,61), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/summonRecall/recall_sm_confirm.png")
	# 抽到的时候出现的 
	I_SM_CONFIRM_2 = RuleImage(roi_front=(377,630,206,62), roi_back=(377,630,206,62), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/summonRecall/sm_sm_confirm_2.png")


	# Ocr Rule Assets
	# 今忆抽卡区域 
	O_RECALL_TICKET_AREA = RuleOcr(roi=(590,660,100,32), area=(590,660,100,32), mode="Single", method="Default", keyword="", name="recall_ticket_area")
	# 选择抽卡区域 
	O_SELECT_SM = RuleOcr(roi=(0,0,100,720), area=(0,0,100,720), mode="Single", method="Default", keyword="", name="select_sm")
	# description 
	O_SELECT_SM1 = RuleOcr(roi=(27,130,45,38), area=(27,130,45,38), mode="Single", method="Default", keyword="", name="select_sm1")
	# description 
	O_SELECT_SM2 = RuleOcr(roi=(26,216,45,38), area=(26,216,45,38), mode="Single", method="Default", keyword="", name="select_sm2")
	# description 
	O_SELECT_SM3 = RuleOcr(roi=(26,304,45,38), area=(26,304,45,38), mode="Single", method="Default", keyword="", name="select_sm3")
	# description 
	O_SELECT_SM4 = RuleOcr(roi=(26,397,45,38), area=(26,397,45,38), mode="Single", method="Default", keyword="", name="select_sm4")


